import type { Destination, Trip, User, BudgetSummary } from "./types";
import { getLocationImage } from "./destinationImages";

// ── Unified Mock User ──────────────────────────────────────────────

export const mockUser: User = {
  id: "user-001",
  name: "Priyanshu Sharma",
  firstName: "Priyanshu",
  email: "priyanshu@globetrotter.com",
  avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=240&auto=format&fit=crop&q=80",
  memberSince: "March 2024",
  tripsCompleted: 8,
};

// ── Real-Time Location-Accurate Destinations (Indian States & Global) ──

export const mockDestinations: Destination[] = [
  {
    id: "dest-in-001",
    name: "Shimla",
    country: "India",
    region: "Himachal Pradesh",
    image: getLocationImage("shimla"),
    rating: 4.9,
    reviewCount: 16420,
    budgetRange: { min: 450, max: 1400, currency: "USD" },
    tags: ["Mountains", "Snow", "Heritage", "Colonial"],
    description:
      "The Queen of Hill Stations — snow-clad Himalayan peaks, historic Christ Church on the Ridge, and pine-scented colonial walks.",
    highlights: ["The Ridge", "Mall Road", "Kufri Snow Point", "Jakhoo Temple"],
  },
  {
    id: "dest-in-002",
    name: "Gujarat",
    country: "India",
    region: "West India",
    image: getLocationImage("gujarat"),
    rating: 4.9,
    reviewCount: 18230,
    budgetRange: { min: 400, max: 1200, currency: "USD" },
    tags: ["Heritage", "Wildlife", "Desert", "Culture"],
    description:
      "Land of legends — endless shimmering white salt desert of Kutch, Asiatic lions in Gir, sacred Somnath, and architectural wonders.",
    highlights: ["Rann of Kutch", "Gir National Park", "Statue of Unity", "Somnath Temple"],
  },
  {
    id: "dest-in-003",
    name: "Jaipur",
    country: "India",
    region: "Rajasthan",
    image: getLocationImage("jaipur"),
    rating: 4.8,
    reviewCount: 22100,
    budgetRange: { min: 350, max: 1100, currency: "USD" },
    tags: ["Royal", "Palaces", "Culture", "Photography"],
    description:
      "The majestic Pink City — opulent royal palaces, towering hill forts, vibrant bazaars, and legendary Rajasthani hospitality.",
    highlights: ["Hawa Mahal", "Amer Fort", "City Palace", "Jantar Mantar"],
  },
  {
    id: "dest-in-004",
    name: "Kerala",
    country: "India",
    region: "South India",
    image: getLocationImage("kerala"),
    rating: 4.9,
    reviewCount: 25400,
    budgetRange: { min: 500, max: 1500, currency: "USD" },
    tags: ["Backwaters", "Nature", "Wellness", "Tea Gardens"],
    description:
      "God's Own Country — tranquil emerald backwaters of Alleppey, lush mist-covered tea gardens of Munnar, and Ayurvedic wellness.",
    highlights: ["Alleppey Houseboats", "Munnar Tea Hills", "Kochi Fort", "Athirappilly Waterfalls"],
  },
  {
    id: "dest-in-005",
    name: "Goa",
    country: "India",
    region: "West India",
    image: getLocationImage("goa"),
    rating: 4.8,
    reviewCount: 28900,
    budgetRange: { min: 350, max: 1200, currency: "USD" },
    tags: ["Beach", "Nightlife", "Portuguese", "Relaxation"],
    description:
      "Golden sun-kissed beaches, swaying coconut palms, historic Portuguese churches, vibrant flea markets, and coastal cuisine.",
    highlights: ["Calangute Beach", "Dudhsagar Falls", "Fort Aguada", "Old Goa Churches"],
  },
  {
    id: "dest-in-006",
    name: "Kashmir",
    country: "India",
    region: "North India",
    image: getLocationImage("kashmir"),
    rating: 5.0,
    reviewCount: 19800,
    budgetRange: { min: 600, max: 1800, currency: "USD" },
    tags: ["Snow", "Lakes", "Romantic", "Adventure"],
    description:
      "Paradise on Earth — shikara rides on tranquil Dal Lake, world-class snow skiing in Gulmarg, and majestic pine valleys of Pahalgam.",
    highlights: ["Dal Lake Shikara", "Gulmarg Gondola", "Betaab Valley", "Sonamarg Glaciers"],
  },
  {
    id: "dest-001",
    name: "Paris",
    country: "France",
    region: "Europe",
    image: getLocationImage("paris"),
    rating: 4.8,
    reviewCount: 12480,
    budgetRange: { min: 1200, max: 3500, currency: "USD" },
    tags: ["Romantic", "Culture", "Food", "Art"],
    description:
      "The City of Light captivates with iconic landmarks, world-class museums, and unmatched culinary experiences along the Seine.",
    highlights: ["Eiffel Tower", "Louvre Museum", "Montmartre", "Seine Cruise"],
  },
  {
    id: "dest-002",
    name: "Tokyo",
    country: "Japan",
    region: "Asia",
    image: getLocationImage("tokyo"),
    rating: 4.9,
    reviewCount: 9870,
    budgetRange: { min: 1500, max: 4000, currency: "USD" },
    tags: ["Technology", "Culture", "Food", "Adventure"],
    description:
      "A dazzling fusion of ultra-modern technology and centuries-old tradition — from neon-lit Shibuya to serene Meiji Shrine.",
    highlights: ["Shibuya Crossing", "Senso-ji Temple", "Akihabara", "Tsukiji Market"],
  },
  {
    id: "dest-003",
    name: "Bali",
    country: "Indonesia",
    region: "Asia",
    image: getLocationImage("bali"),
    rating: 4.7,
    reviewCount: 15320,
    budgetRange: { min: 800, max: 2500, currency: "USD" },
    tags: ["Beach", "Wellness", "Nature", "Adventure"],
    description:
      "Lush rice terraces, sacred temples, and pristine beaches make Bali the ultimate island paradise for relaxation and adventure.",
    highlights: ["Tegallalang Rice Terraces", "Uluwatu Temple", "Ubud", "Seminyak Beach"],
  },
  {
    id: "dest-004",
    name: "New York",
    country: "United States",
    region: "North America",
    image: getLocationImage("newyork"),
    rating: 4.6,
    reviewCount: 18940,
    budgetRange: { min: 1800, max: 5000, currency: "USD" },
    tags: ["Urban", "Culture", "Food", "Shopping"],
    description:
      "The city that never sleeps offers Broadway shows, iconic skyline views, world-class dining, and endless urban energy.",
    highlights: ["Central Park", "Times Square", "Brooklyn Bridge", "Statue of Liberty"],
  },
  {
    id: "dest-005",
    name: "Santorini",
    country: "Greece",
    region: "Europe",
    image: getLocationImage("santorini"),
    rating: 4.9,
    reviewCount: 8760,
    budgetRange: { min: 1400, max: 3800, currency: "USD" },
    tags: ["Romantic", "Beach", "Photography", "Food"],
    description:
      "Iconic white-and-blue architecture perched on volcanic cliffs above the deep blue Aegean — a picture-perfect Mediterranean gem.",
    highlights: ["Oia Sunset", "Caldera View", "Red Beach", "Wine Tasting"],
  },
  {
    id: "dest-006",
    name: "Dubai",
    country: "United Arab Emirates",
    region: "Middle East",
    image: getLocationImage("dubai"),
    rating: 4.5,
    reviewCount: 11250,
    budgetRange: { min: 2000, max: 6000, currency: "USD" },
    tags: ["Luxury", "Shopping", "Adventure", "Architecture"],
    description:
      "A futuristic metropolis rising from the desert — record-breaking skyscrapers, luxury shopping, and Arabian desert adventures.",
    highlights: ["Burj Khalifa", "Dubai Mall", "Desert Safari", "Palm Jumeirah"],
  },
  {
    id: "dest-007",
    name: "Swiss Alps",
    country: "Switzerland",
    region: "Europe",
    image: getLocationImage("switzerland"),
    rating: 4.9,
    reviewCount: 14200,
    budgetRange: { min: 2200, max: 5500, currency: "USD" },
    tags: ["Mountains", "Skiing", "Nature", "Scenic"],
    description:
      "Towering snow peaks, pristine glacier lakes, scenic alpine train journeys, and world-class ski slopes in the heart of Europe.",
    highlights: ["Matterhorn", "Jungfraujoch", "Interlaken", "Lake Geneva"],
  },
];

// ── Real-Time Location-Accurate Trips ───────────────────────────────

export const mockTrips: Trip[] = [
  {
    id: "trip-in-001",
    name: "Shimla Himalayan Escape",
    destination: "Shimla",
    country: "India",
    image: getLocationImage("shimla"),
    startDate: "2026-11-10",
    endDate: "2026-11-16",
    status: "upcoming",
    budget: { total: 1200, spent: 250, currency: "USD" },
    travelers: 2,
    activities: ["The Ridge & Christ Church", "Kufri Snow Trek", "Mall Road Walk", "Jakhoo Hill"],
  },
  {
    id: "trip-in-002",
    name: "Rann of Kutch & Gir Safari",
    destination: "Gujarat",
    country: "India",
    image: getLocationImage("gujarat"),
    startDate: "2026-12-05",
    endDate: "2026-12-12",
    status: "upcoming",
    budget: { total: 1100, spent: 180, currency: "USD" },
    travelers: 3,
    activities: ["White Desert Sunset", "Gir Lion Safari", "Somnath Temple", "Statue of Unity"],
  },
  {
    id: "trip-in-003",
    name: "Royal Heritage of Rajasthan",
    destination: "Jaipur",
    country: "India",
    image: getLocationImage("jaipur"),
    startDate: "2026-04-12",
    endDate: "2026-04-18",
    status: "completed",
    budget: { total: 1400, spent: 1350, currency: "USD" },
    travelers: 2,
    activities: ["Hawa Mahal", "Amer Fort Elephant Walk", "Lake Pichola Boat Ride", "Desert Safari"],
  },
  {
    id: "trip-in-004",
    name: "Kerala Backwaters & Tea Gardens",
    destination: "Kerala",
    country: "India",
    image: getLocationImage("kerala"),
    startDate: "2026-03-01",
    endDate: "2026-03-08",
    status: "completed",
    budget: { total: 1600, spent: 1520, currency: "USD" },
    travelers: 2,
    activities: ["Alleppey Houseboat Cruise", "Munnar Tea Plantation", "Kathakali Show", "Kochi Fort"],
  },
  {
    id: "trip-001",
    name: "Parisian Autumn",
    destination: "Paris",
    country: "France",
    image: getLocationImage("paris"),
    startDate: "2026-09-15",
    endDate: "2026-09-22",
    status: "upcoming",
    budget: { total: 2800, spent: 450, currency: "USD" },
    travelers: 2,
    activities: ["Museum Tours", "River Cruise", "Wine Tasting", "Photography Walk"],
  },
  {
    id: "trip-002",
    name: "Bali Retreat",
    destination: "Bali",
    country: "Indonesia",
    image: getLocationImage("bali"),
    startDate: "2026-07-01",
    endDate: "2026-07-10",
    status: "completed",
    budget: { total: 2200, spent: 1980, currency: "USD" },
    travelers: 2,
    activities: ["Temple Visit", "Rice Terrace Trek", "Surf Lessons", "Spa Day"],
  },
  {
    id: "trip-003",
    name: "Swiss Alps Adventure",
    destination: "Switzerland",
    country: "Switzerland",
    image: getLocationImage("switzerland"),
    startDate: "2026-06-10",
    endDate: "2026-06-18",
    status: "completed",
    budget: { total: 3500, spent: 3280, currency: "USD" },
    travelers: 4,
    activities: ["Hiking", "Skiing", "Cheese Tasting", "Train Rides"],
  },
  {
    id: "trip-004",
    name: "Tokyo Discovery",
    destination: "Tokyo",
    country: "Japan",
    image: getLocationImage("tokyo"),
    startDate: "2026-10-05",
    endDate: "2026-10-14",
    status: "upcoming",
    budget: { total: 3800, spent: 600, currency: "USD" },
    travelers: 1,
    activities: ["Temple Tour", "Street Food", "Anime District", "Cherry Blossom"],
  },
];

// ── Budget Summary ─────────────────────────────────────────────────

export const mockBudgetSummary: BudgetSummary = {
  totalBudget: 16800,
  totalSpent: 8900,
  remaining: 7900,
  currency: "USD",
  categoryBreakdown: [
    { category: "Flights", amount: 3450 },
    { category: "Hotels", amount: 2890 },
    { category: "Food & Dining", amount: 1480 },
    { category: "Activities", amount: 950 },
    { category: "Transport", amount: 480 },
  ],
};
